baseURL = "https://insuusvenerati.github.io/landing/"
languageCode = "en-us"
title = "Sean Norwood"
theme = "hugo-sustain"

[params]
  avatar = "866898.png"
  author = "Sean Norwood"
  description = "Describe your website"

[params.social]
  Github        = "insuusvenerati"
  Email         = "norwood.sean@gmail.com"
  Twitter       = "stiforr"

[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "https://insuusvenerati.github.io/resume/"

[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"

[[menu.main]]
  name = "blog"
  identifier = "blog"
  weight = 100
  url = "https://insuus.netlify.com"
